Fix: team ID ndray  androany mande amzay lets e

diff --git a/.github/workflows/ios-build.yml b/.github/workflows/ios-build.yml
--- a/.github/workflows/ios-build.yml
+++ b/.github/workflows/ios-build.yml
@@ -75,11 +75,20 @@ jobs:
               cp provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
               echo "✅ Provisioning profile copied successfully!"
       
-      - name: Set Development Team in Xcode project
+      - name: Configure Xcode Signing
         run: |
-              sed -i '' 's/DevelopmentTeam = "";$/DevelopmentTeam = 9PW89SQJ4U;/g' ios/Runner.xcodeproj/project.pbxproj
-              cat ios/Runner.xcodeproj/project.pbxproj | grep DEVELOPMENT_TEAM
-      
+            /usr/libexec/PlistBuddy -c "Set :DEVELOPMENT_TEAM 9PW89SQJ4U" "ios/Runner.xcodeproj/project.pbxproj" || echo "PlistBuddy update failed"
+            /usr/libexec/PlistBuddy -c "Print" "ios/Runner.xcodeproj/project.pbxproj" | grep DEVELOPMENT_TEAM || echo "No DEVELOPMENT_TEAM found"
+            
+      - name: Enable Automatic Signing
+        run: |
+            xcodebuild -project ios/Runner.xcodeproj \
+            -scheme Runner \
+            -destination 'generic/platform=iOS' \
+            CODE_SIGN_STYLE=Automatic \
+            DEVELOPMENT_TEAM=9PW89SQJ4U
+
+
       - name: Verify Code Signing Identity
         run: security find-identity -v -p codesigning
  
