Fix: leo ah jesosy reraka

diff --git a/.github/workflows/ios-build.yml b/.github/workflows/ios-build.yml
--- a/.github/workflows/ios-build.yml
+++ b/.github/workflows/ios-build.yml
@@ -21,7 +21,12 @@ jobs:
 
       - name: Install dependencies
         run: flutter pub get
-
+      
+      - name: Debug Provisioning Profile
+        run: |
+          echo "Provisioning profile content size:"
+          echo "${{ secrets.APPLE_PROVISIONING_PROFILE }}" | wc -c
+      
 
       - name: Force iOS 13+ in Podfiles
         run: |
@@ -69,16 +74,16 @@ jobs:
             mkdir -p assets/credentials
             echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > assets/credentials/service_account_key.json
       
-      - name: Setup Provisioning Profile
-        run: |
-              mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-              if [ -f provisioning.mobileprovision ]; then
-                cp provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
-                echo "Provisioning profile copied successfully!"
-              else
-                echo "ERROR: provisioning.mobileprovision not found!"
-                exit 1
-              fi
+      # - name: Setup Provisioning Profile
+      #   run: |
+      #         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+      #         if [ -f provisioning.mobileprovision ]; then
+      #           cp provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
+      #           echo "Provisioning profile copied successfully!"
+      #         else
+      #           echo "ERROR: provisioning.mobileprovision not found!"
+      #           exit 1
+      #         fi
           
     
   
